ENV['SINATRA_ENV'] ||= 'development'
ENV['RACK_ENV'] ||= 'development'

require 'bundler/setup'
Bundler.require(:default, ENV['SINATRA_ENV'])
require 'sinatra/activerecord'
require 'sinatra/activerecord/rake'
require_all 'app'

set :database, adapter: 'sqlite3', database: 'restaurants.sqlite3'
