# A sample Gemfile
source 'https://rubygems.org'

gem 'activerecord', '4.2', require: 'active_record'
gem 'bcrypt'
gem 'rake'
gem 'require_all'
gem 'shotgun'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-flash'
gem 'sqlite3', '~>1.3.6'
gem 'thin'
gem 'truemail'
