# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'terminal-table'
gem 'gems'
gem 'octokit'
gem 'nokogiri'
gem 'terminal-table'
