# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'httparty'
gem 'redis-activesupport'
gem 'telegram-bot'

group :development do
  gem 'byebug'
  gem 'pry'
end
