# frozen_string_literal: true

gem 'sqlite3', '~> 1.4.1'
gem 'rake', '~> 12.3.3'
gem 'sinatra', '~> 2.0.5'
gem 'sinatra-activerecord', '~> 2.0.13'
gem 'sequel', '~> 5.22.0'
group :development do
  gem 'shotgun', '~> 0.9.2'
  gem 'pry', '~> 0.12.2'
end