# frozen_string_literal: true

gem 'bcrypt', '~> 3.1.13'
gem 'dotenv', '~> 2.7.4'
gem 'pagy', '~> 3.4.1'
gem 'rake', '~> 12.3.3'
gem 'sinatra', '~> 2.0.5'
gem 'sinatra-activerecord', '~> 2.0.13'
gem 'sinatra-contrib', '~> 2.0.5'
gem 'sinatra-strong-params', '~> 0.1.0', require: 'sinatra/strong-params'
gem 'sqlite3', '~> 1.4.1'

group :development do
  gem 'pry', '~> 0.12.2'
  gem 'shotgun', '~> 0.9.2'
end
