source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'activesupport'
gem 'figaro', '~> 1.1', '>= 1.1.1'
gem 'json', '~> 1.8', '>= 1.8.3'
gem 'redis', '~> 4.1', '>= 4.1.2'
gem 'reek', '~> 5.4'
gem 'rubocop'
gem 'telegram-bot', '~> 0.14.2'
gem 'telegram-bot-types', '~> 0.6.1'
