# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activesupport', require: 'active_support/all'
gem 'dotenv', require: 'dotenv/load'
gem 'ohm'
gem 'pry-byebug', '~> 3.7'
gem 'redis', '~> 4.1', '>= 4.1.2'
gem 'redis-rails'
gem 'reek', '~> 5.4', require: false
gem 'rubocop', require: false
gem 'telegram-bot', '~> 0.14.2', require: 'telegram/bot'
gem 'telegram-bot-types', '~> 0.6.1'
