# frozen_string_literal: true

source 'https://rubygems.org'

gem 'dotenv'
gem 'email_address'
gem 'pry'
gem 'rake'
gem 'sinatra-activerecord'
gem 'sinatra-flash', '~> 0.3.0'
gem 'sqlite3'
gem 'truemail'
