source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'fileutils'
gem 'optparse'
gem 'tty-table'
gem 'watir'
gem 'webdrivers/geckodriver'
gem 'yaml'
