detectors:
  IrresponsibleModule:
    enabled: false

  DuplicateMethodCall:
    enabled: false

  UtilityFunction:
    public_methods_only: true

  TooManyMethods:
    enabled: false

  UncommunicativeModuleName:
    enabled: false

  InstanceVariableAssumption:
    enabled: false

  FeatureEnvy:
    enabled: false

  RepeatedConditional:
    enabled: false

  TooManyStatements:
    enabled: false

  UncommunicativeVariableName:
    enabled: false

  UncommunicativeMethodName:
    enabled: false


