detectors:
  IrresponsibleModule:
    enabled: false

  DuplicateMethodCall:
    enabled: false

  UtilityFunction:
    public_methods_only: true

  TooManyMethods:
    enabled: false

  UncommunicativeModuleName:
    enabled: false

  InstanceVariableAssumption:
    enabled: false

  FeatureEnvy:
    enabled: false

  RepeatedConditional:
    enabled: false

  TooManyStatements:
    enabled: false

  UncommunicativeVariableName:
    enabled: false

  UncommunicativeMethodName:
    enabled: false

  NilCheck:
    enabled: false

  Attribute:
    enabled: false

  ManualDispatch:
    enabled: false

  ControlParameter:
    enabled: false

  NestedIterators:
    enabled: false

  TooManyInstanceVariables:
    enabled: false

  UnusedParameters:
    enabled: false

  DataClump:
    enabled: false

  UncommunicativeParameterName:
    enabled: false
