Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 60

Style/BlockDelimiters:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Lint/RescueException:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/EvalWithLocation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/MethodMissingSuper:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Security/Eval:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false

Lint/LiteralAsCondition:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false

Performance/RedundantMatch:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/MethodMissing:
  Enabled: false