# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'aasm'
gem 'dotenv', require: 'dotenv/load'
gem 'pry'
gem 'pry-byebug'
gem 'redis'
gem 'rest-client'
gem 'rspec'
gem 'telegram-bot-ruby'
