# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'activesupport', '~> 5.2.3'
gem 'dotenv', '~> 2.7.4'
gem 'logger', '~> 1.3.0'
gem 'redis', '~> 4.1.2'
gem 'telegram-bot', '~> 0.14.2'