source 'https://rubygems.org'

gem 'activerecord', '~> 5.2', '>= 5.2.3'
gem 'bcrypt', '~> 3.1', '>= 3.1.12'
gem 'haml', '~> 5.1', '>= 5.1.1'
gem 'sinatra', '~> 2.0', '>= 2.0.5'
gem 'sinatra-flash', '~> 0.3.0'
gem 'sqlite3', '~> 1.4', '>= 1.4.1'
gem 'standalone_migrations', '~> 5.2', '>= 5.2.7'

group :development do
  gem 'pry'
end
