source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'activerecord'
gem 'bcrypt'
gem 'pry'
gem 'rake'
gem 'shotgun'
gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-activerecord'
gem 'sinatra-contrib', require: false
gem 'sinatra-flash'
gem 'sqlite3'
gem 'thin'
gem 'truemail'
