require './environment'
require 'pry'
task :console do
  require './app'
  Pry.start
end

namespace :db do
  desc 'Migrate the database'

  task :migrate do
  end

  task :seed do
    require './db/seed'
    # Dir.glob('db/**/*.rb') { |f| require_relative(f) }
    Seed.seed
  end

  task :setup do
    require './db/seed'
    Seed.setup
  end

  task :drop do
    require './db/seed'
    # Dir.glob('db/**/*.rb') { |f| require_relative(f) }
    Seed.drop
  end
end
