ENV['SINATRA_ENV'] ||= 'development'

require_relative './config/environment'
require_relative './db/seeds'

require 'sinatra/activerecord/rake'

task :console do
  Pry.start
end

namespace :db do
  task :seed do
    Seeds.call
  end
end
