# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'mechanize'
gem 'pry'
gem 'reek'
gem 'rubocop'
gem 'terminal-table'
