User.create(name: 'Boris the Razor', email: 'cantouchthis@gmail.com', password: BCrypt::Password.create('boris').to_s)
User.create(name: 'Mikey oNil', email: 'sexyguy@gmail.com', password: BCrypt::Password.create('bread').to_s)
User.create(name: 'Tyrecki', email: 'quotemegmail.com', password: BCrypt::Password.create('steakman').to_s)
User.create(name: 'Franky', email: 'deltorro@gmail.com', password: BCrypt::Password.create('benny').to_s)
User.create(name: 'Tony', email: 'bulletinteeth@gmail.com', password: BCrypt::Password.create('vinny').to_s)
Restaurant.create(name: 'KFC', short_description: 'some short description of KFC', long_description: 'some long description of KFC', image_path: 'https://www.delivery-club.ru/logos_full/kfc_msk.jpg?1564118244', address: 'some address of KFC')
Restaurant.create(name: 'MacDonalds', short_description: 'some short description of MacDonalds', long_description: 'some long description of MacDonalds', image_path: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/McDonald%27s_Golden_Arches.svg/120px-McDonald%27s_Golden_Arches.svg.png', address: 'some address of MacDonalds')
Restaurant.create(name: 'Burger King', short_description: 'some short description of Burger King', long_description: 'some long description of Burger King', image_path: 'https://upload.wikimedia.org/wikipedia/ru/thumb/3/3a/Burger_King_Logo.svg/1200px-Burger_King_Logo.svg.png', address: 'some address of Burger King')
Restaurant.create(name: 'Texas Chicken', short_description: 'some short description of Texas Chicken', long_description: 'some long description of Texas Chicken', image_path: 'https://texas-chicken.by/images/site/logo1.png', address: 'some address of Texas Chicken')
Restaurant.create(name: 'Pizza Tempo', short_description: 'some short description of Pizza Tempo', long_description: 'some long description of Pizza Tempo', image_path: 'https://pbs.twimg.com/profile_images/1023281119821787137/M-Pps5B2_400x400.jpg', address: 'some address of Pizza Tempo')
Review.create(title: ' KFC is the best place', text: 'Some good review text', rating: 5.0, user_id: 1, restaurant_id: 1)
Review.create(title: ' Mac is the best place', text: 'Some good review text', rating: 4.5, user_id: 4, restaurant_id: 2)
Review.create(title: ' BK is the trash', text: 'Some bad review text', rating: 2.5, user_id: 5, restaurant_id: 3)
Review.create(title: ' TC is the trash', text: 'Some bad review text', rating: 1.0, user_id: 2, restaurant_id: 4)
Review.create(title: ' PT is the best place', text: 'Some good review text', rating: 4.0, user_id: 3, restaurant_id: 5)
