User.create(name: 'Boris the Razor', email: 'cantouchthis@gmail.com', password: 'boris')
User.create(name: 'Mikey oNil', email: 'sexyguy@gmail.com', password: 'bread')
User.create(name: 'Tyrecki', email: 'quotemegmail.com', password: 'steakman')
User.create(name: 'Franky', email: 'deltorro@gmail.com', password: 'benny')
User.create(name: 'Tony', email: 'bulletinteeth@gmail.com', password: 'vinny')
Restaurant.create(name: 'KFC', short_description: 'some short description of KFC', long_description: 'some long description of KFC', address: 'some address of KFC')
Restaurant.create(name: 'MacDonalds', short_description: 'some short description of MacDonalds', long_description: 'some long description of MacDonalds', address: 'some address of MacDonalds')
Restaurant.create(name: 'Burger King', short_description: 'some short description of Burger King', long_description: 'some long description of Burger King', address: 'some address of Burger King')
Restaurant.create(name: 'Tehas Chicken', short_description: 'some short description of Tehas Chicken', long_description: 'some long description of Tehas Chicken', address: 'some address of Tehas Chicken')
Restaurant.create(name: 'Pizza Tempo', short_description: 'some short description of Pizza Tempo', long_description: 'some long description of Pizza Tempo', address: 'some address of Pizza Tempo')
Review.create(title: ' KFC is the best place', text: 'Some good review text', rating: 5.0, user_id: 1, restaurant_id: 1)
Review.create(title: ' Mac is the best place', text: 'Some good review text', rating: 4.5, user_id: 4, restaurant_id: 2)
Review.create(title: ' BK is the trash', text: 'Some bad review text', rating: 2.5, user_id: 5, restaurant_id: 3)
Review.create(title: ' TC is the trash', text: 'Some bad review text', rating: 1.0, user_id: 2, restaurant_id: 4)
Review.create(title: ' PT is the best place', text: 'Some good review text', rating: 4.0, user_id: 3, restaurant_id: 5)
