# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord'
gem 'bcrypt'
gem 'bundler'
gem 'rake'
gem 'shotgun'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-flash'
gem 'sqlite3'
