# frozen_string_literal: true

source 'https://rubygems.org'

# parse html
gem 'nokogiri'

# better output
gem 'terminal-table'

# instead of net/http
gem 'faraday'

# make-like build utility
gem 'rake'

# testing
gem 'minitest'
