# rubocop:disable Lint/UnneededCopDisableDirective
# rubocop:disable Lint/ScriptPermission
# rubocop:disable Style/HashSyntax
# !/usr/bin/env ruby
# -*- ruby -*-

require 'rake/clean'
require 'rake/testtask'

task :default => :test

task :test do
  ruby 'path_to_enlightenment.rb'
end
# rubocop:enable Lint/ScriptPermission
# rubocop:enable Lint/UnneededCopDisableDirective
# rubocop:enable Style/HashSyntax
