# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'gems'
gem 'nokogiri'
gem 'open-uri'
gem 'optparse'
gem 'terminal-table'
gem 'yaml'
