# rubocop:disable all

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'logger'
gem 'redis-activesupport'
gem 'telegram-bot'

# rubocop:enable all
