# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'activerecord', require: 'active_record'
gem 'bcrypt'
gem 'pry'
gem 'rack-flash3'
gem 'rake'
gem 'require_all' #=> Helps to load dependencies
gem 'shotgun'
gem 'sinatra'
gem 'sinatra-activerecord', require: 'sinatra/activerecord'
gem 'sinatra-flash'
gem 'sqlite3'
gem 'thin'
gem 'tux'
