#!/usr/bin/env ruby
# rubocop: disable all

# -*- ruby -*-

require 'rake/clean'
require 'rake/testtask'

task default: :test

task :test do
  ruby 'path_to_enlightenment.rb'
end
# rubocop: enable all
