source 'https://rubygems.org'

gem 'activerecord'
gem 'bcrypt'
gem 'csv'
gem 'dotenv'
gem 'rack-flash3'
gem 'rake'
gem 'rerun'
gem 'sinatra-activerecord'
gem 'sinatra-flash'
gem 'sqlite3'

group :test, :development do
  gem 'pry'
end
