source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.3'

gem 'rake', '12.3.3'
gem 'bundler'
gem 'sqlite3'
gem 'dotenv', '2.7.4'
gem 'require_all', '2.0.0'
gem 'i18n', '1.6.0'
gem 'sinatra', '~> 2.0', '>= 2.0.5'
gem 'activerecord', '~> 5.2', '>= 5.2.3'
gem 'sinatra-activerecord', '~> 2.0', '>= 2.0.13'
gem 'sinatra-flash', '~> 0.3.0'
gem 'bcrypt', '~> 3.1', '>= 3.1.13'
gem 'pry'
