source 'https://rubygems.org'

ruby '2.5.3'

gem 'activerecord', '~> 5.2', '>= 5.2.3'
gem 'bcrypt', '~> 3.1', '>= 3.1.13'
gem 'bundler'
gem 'dotenv', '2.7.4', require: 'dotenv/load'
gem 'i18n', '1.6.0'
gem 'pry'
gem 'rake', '12.3.3'
gem 'require_all', '2.0.0'
gem 'rubocop', require: false
gem 'sinatra', '~> 2.0', '>= 2.0.5'
gem 'sinatra-activerecord', '~> 2.0', '>= 2.0.13'
gem 'sinatra-flash', '~> 0.3.0'
gem 'sqlite3'
