source 'https://rubygems.org'

gem 'activerecord'
gem 'bcrypt'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'sinatra-session'
gem 'shotgun'
gem 'sqlite3'

group :development do
  gem 'pry-byebug'
  gem 'tux'
end
