# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord', require: 'active_record'
gem 'bcrypt'
gem 'dotenv', require: 'dotenv/load'
gem 'pry'
gem 'rack-flash3'
gem 'rake'
gem 'require_all'
gem 'shotgun'
gem 'sinatra'
gem 'sinatra-activerecord', require: 'sinatra/activerecord'
gem 'sinatra-flash'
gem 'sqlite3'
gem 'thin'
gem 'tux'
