source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
group :development do
  gem 'httparty'
  gem 'mechanize'
  gem 'nokogiri'
  gem 'octokit'
  gem 'reek'
  gem 'rubocop'
  gem 'terminal-table'
end
