# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord'
gem 'bcrypt'
gem 'rake'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'sinatra-flash'
gem 'sqlite3'
gem 'truemail'
