source 'https://rubygems.org' do
  gem 'httparty', '0.17.0'
  gem 'loc', '>=0.1.0'
  gem 'redis', '4.1.2'
  gem 'redis-activesupport', '5.0.7'
  gem 'telegram-bot', '0.14.2'

  group :development do
    gem 'pry'
  end
end
