# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'activerecord', '~> 5.2', '>= 5.2.3', require: 'active_record'
gem 'bcrypt', '~> 3.1', '>= 3.1.13'
gem 'rack-flash3', '~> 1.0', '>= 1.0.5'
gem 'rake', '~> 12.3', '>= 12.3.3'
gem 'require_all', '~> 2.0'
gem 'sinatra', '~> 2.0', '>= 2.0.5'
gem 'sinatra-activerecord', '~> 2.0', '>= 2.0.13', require: 'sinatra/activerecord'
gem 'sinatra-contrib', '~> 2.0', '>= 2.0.5', require: false
gem 'slim', '~> 4.0', '>= 4.0.1'
gem 'thin', '~> 1.7', '>= 1.7.2'

group :development do
  gem 'pry', '~> 0.12.2'
  gem 'shotgun', '~> 0.9.2'
  gem 'sqlite3', '~> 1.4', '>= 1.4.1'
  gem 'tux', '~> 0.3.0'
end

group :production do
  gem 'pg', '~> 1.1', '>= 1.1.4'
end
