# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'activerecord', require: 'active_record'
gem 'bcrypt'
gem 'rack-flash3'
gem 'rake'
gem 'require_all'
gem 'shotgun'
gem 'sinatra'
gem 'sinatra-activerecord', require: 'sinatra/activerecord'
gem 'sinatra-contrib', require: false
gem 'sinatra-flash'
gem 'slim'
gem 'sqlite3'
gem 'thin'
gem 'tux'

group :development do
  gem 'pry'
end
