source 'https://rubygems.org'

gem 'bcrypt', '~> 3.1.13'
gem 'dotenv', '2.7.4'
gem 'rake', '~> 12.3.3'
gem 'shotgun', '~> 0.9.2'
gem 'sinatra', '~> 2.0.5'
gem 'sinatra-activerecord', '~> 2.0.13'
gem 'sqlite3', '~> 1.4.1'
